name: Generate ASCII artwork with 1 example
 
on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v7
        
        - name: list repo files
          run: ls -lrta


        - name: execute shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh